### ISSUE TITLE
Implement adding/removing whitespace after/before `:`, ',', '|`, `=` etc

### ISSUE THREAD

**Issue by 9898287** [def-/nimfmt#1]
This helps in inconsistent (and mostly unintentional) writing style in the following scenario:
```var x: int = 0
var a,b,c: float
proc fn(): bool =
proc fn[T : int | float](arg: T): auto =
var x = PointObj(x:10, y:11, b:10)

**Comment by def-** [comment]
This repo doesn't really do anything useful, it just uses the nim compiler directly, so changes to the output format of the compiler/renderer should be made there.
